payment:
  vnpay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: { vnp_tmnCode }
    secretKey: { vnp_HashSecret }
    returnUrl: http://localhost:8080/api/v1/payment/%s/status
    version: 2.1.0
    command: pay
    orderType: other
    expiration: 15